development:
  downloads_path: "/Users/fguillen/Downloads"
  transmission_api_url: http://localhost:9091/transmission/rpc
  transmission_auth:
    username: "username"
    password: "password"

test:
  downloads_path: "/Users/fguillen/Downloads"
  transmission_api_url: "http://api.url"
  transmission_auth:
    username: "username"
    password: "password"

production:
  downloads_path: "/Users/fguillen/Downloads"
  transmission_api_url: http://localhost:9091/transmission/rpc
  transmission_auth:
    username: "username"
    password: "password"
